[project]
name = "health-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.23.1",
    "requests>=2.32.5",
    "requests-oauthlib>=2.0.0",
]
